# Generated by Django 6.0.6 on 2026-06-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_approved_user_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
