# Generated by Django 6.0.6 on 2026-06-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
